/**
 * AUTO-GENERATED LIGHTWEIGHT PAGE METADATA MAP
 * Extracted at build time for 0-cost routing, instant startup & 0 forced reflows
 */

export interface PageMetadata {
  pageKey: string;
  title: string;
  displayTitle: string;
  description: string;
  keywords: string;
  link: string;
  type?: string;
  jackpotId?: string;
  fixturesCategory?: string;
  icon?: string;
  badgeColor?: string;
  authorId?: string;
  authorName?: string;
  authorTitle?: string;
  authorDescription?: string;
  authorAvatar?: string;
  responsibleGambling?: string;
  inboundTitle?: string;
  inboundHeading?: string;
  inboundDescription?: string;
  inboundSubtitle?: string;
  inboundBadge?: string;
  miniIntro?: string;
  unlockHeading?: string;
  unlockDescription?: string;
  listTitle?: string;
  listSubtitle?: string;
}

export const PAGE_METADATA_MAP: Record<string, PageMetadata> = {
  "254-golden-tips": {
    "pageKey": "254-golden-tips",
    "title": "254 Golden Tips",
    "displayTitle": "254 Golden Tips and Predictions",
    "description": "254 Golden Tips picks a few of well analysed soka predictions. The 254goldentips are free and available daily",
    "keywords": "254goldentip, 254 golden tip, 254goldentips, 254 golden tips",
    "link": "/254-golden-tips",
    "type": "competitor",
    "icon": "🌐",
    "badgeColor": "bg-purple-500/10 text-purple-500 border-purple-500/20",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "inboundTitle": "254 Golden Tips and Prediction Altenatives",
    "inboundHeading": "254 Golden Tips and Prediction Altenatives",
    "inboundDescription": "Compare daily 254 Golden Tips tip distributions with other top soccer analytics.",
    "inboundSubtitle": "Compare daily 254 Golden Tips tip distributions with other top soccer analytics.",
    "unlockHeading": "Soka Master Today's Premium VIP Odds Packs",
    "unlockDescription": "Get instant access to multi-bets with high winning probability.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "Check Sokamasta daily double-chance options and standard single tips verified by Soka King punters."
  },
  "254-sure-tips": {
    "pageKey": "254-sure-tips",
    "title": "254 Sure Tips Today - Fixed Odds & High Confidence Predictions",
    "displayTitle": "254 Sure Tips Today - Fixed Odds & High Confidence Predictions",
    "description": "Get daily 254 sure tips, high winning accuracy football predictions, and expert banker picks for Kenyan and global matches.",
    "keywords": "254 sure tips, sure bets Kenya, high odds tips, banker predictions, free sure tips Kenya",
    "link": "/254-sure-tips",
    "type": "competitor",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Betting involves financial risk. Please bet responsibly and risk only what you can afford. Helpline: 0800-720-000.",
    "inboundTitle": "254 Sure Tips Alternatives & Related Analysis Portals",
    "inboundHeading": "254 Sure Tips Alternatives & Related Analysis Portals",
    "inboundDescription": "Compare 254 Sure Tips daily algorithmic models, banker accuracy rates, and Poisson distributions with top soccer analytics networks.",
    "inboundSubtitle": "Compare 254 Sure Tips daily algorithmic models, banker accuracy rates, and Poisson distributions with top soccer analytics networks.",
    "unlockHeading": "Unlock 254 High-Odds Banker Slips & Multi-Bet Tips",
    "unlockDescription": "Get instant M-Pesa access to daily 254 sure tips, high-odds accumulator legs, and multi-market combinations.",
    "listTitle": "254 Sure Tips Free Predictions Today",
    "listSubtitle": "Daily 254 sure tips and high-confidence predictions verified by Soka King mathematical indexes."
  },
  "4soka-tips-prediction": {
    "pageKey": "4soka-tips-prediction",
    "title": "4Soka Tips Predictions",
    "displayTitle": "4Soka Tips Predictions",
    "description": "Get the latest soka tips today, free football predictions, 1X2 tips, over and under predictions, BTTS picks, and carefully analyzed fixture tips. Updated daily",
    "keywords": "4soka tips prediction, 4soka prediction, 4sokatips, 4soka tips",
    "link": "/4soka-tips",
    "type": "competitor",
    "icon": "🌐",
    "badgeColor": "bg-purple-500/10 text-purple-500 border-purple-500/20",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "inboundTitle": "4soka Alternative Prediction",
    "inboundHeading": "4soka Alternative Prediction",
    "inboundDescription": "Compare how other competitor tips look like",
    "inboundSubtitle": "Compare how other competitor tips look like",
    "unlockHeading": "4Soka Tips Today's Premium VIP Odds Packs",
    "unlockDescription": "Get instant access to multi-tips with high winning rates.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "Check 4Soka Tips daily BTTS, OVER/UNDER and double-chance options verified by Soka King punters."
  },
  "about": {
    "pageKey": "about",
    "title": "Who We Are & How Our Predictions Work",
    "displayTitle": "Who We Are & How Our Predictions Work",
    "description": "Soka King is East Africa's leading sports analytics platform for football predictions.",
    "keywords": "about Soka King, sports intelligence, football probability modeling",
    "link": "/about-us",
    "type": "static",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "unlockHeading": "Soka King Intelligence Network",
    "unlockDescription": "Explore our predictive algorithms",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "betika-midweek": {
    "pageKey": "betika-midweek",
    "title": "Betika Midweek Jackpot Predictions & Daily Tips (15 Games)",
    "displayTitle": "Betika Midweek Jackpot Selections & Covers (15 Games)",
    "description": "Betika Midweek Jackpot predictions for 15 games. Computer models and Poisson probability predictions for KES 15 Million prize pool.",
    "keywords": "Betika Midweek Jackpot predictions, Betika 15 games tips, Betika midweek double chance",
    "link": "/free-betika-midweek-jackpot-predictions-and-analysis",
    "type": "jackpot",
    "jackpotId": "betika-midweek",
    "authorId": "david-ochieng",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Betting should be entertaining. Please gamble responsibly. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock All 15 Fixture Predictions & Double Chance Slips",
    "unlockDescription": "Subscribe to get instant access to full 1X2 selections, banker probability rankings, and low-variance double-chance covers for Betika Midweek Jackpot.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "betpawa-pick-jackpot": {
    "pageKey": "betpawa-pick-jackpot",
    "title": "betPawa Pick 13 Jackpot Predictions & Selections",
    "displayTitle": "betPawa Pick 13 Jackpot Selections & Covers",
    "description": "betPawa Pick 13 jackpot predictions. Low-stake high-return jackpot tips, double chance combinations, and banker selections.",
    "keywords": "betPawa Pick 13 jackpot predictions, betPawa tips, betPawa jackpot Kenya",
    "link": "/free-betpawa-pick-jackpot-predictions-and-analysis",
    "type": "jackpot",
    "jackpotId": "betpawa-pick-jackpot",
    "authorId": "samuel-omondi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Play responsibly. Gambling is restricted to 18+. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock betPawa Pick 13 Jackpot Predictions",
    "unlockDescription": "Get instant access to optimized 13-game jackpot slips with double chance combinations for betPawa Kenya.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "category-btts": {
    "pageKey": "category-btts",
    "title": "Both Teams To Score (BTTS / GG) Predictions - Soka King",
    "displayTitle": "Both Teams To Score (BTTS / GG) Predictions Today",
    "description": "High-accuracy Both Teams To Score (BTTS / Goal-Goal) football tips. Computer algorithms analyzing attacking momentum and defensive leaks.",
    "keywords": "BTTS predictions, GG predictions today, both teams to score tips",
    "link": "/football-predictions-btts-gg",
    "type": "category",
    "fixturesCategory": "btts",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Gamble responsibly. Never bet money needed for essentials. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock High-Yield BTTS (GG) Accumulator Slips",
    "unlockDescription": "Access daily Goal-Goal selections with high offensive output indicators and leaky defensive trends.",
    "listTitle": "Both Teams To Score (BTTS / GG) Free Predictions",
    "listSubtitle": "High-probability Goal-Goal match selections and scoring tips verified by Soka King mathematical indexes."
  },
  "category-doublechance": {
    "pageKey": "category-doublechance",
    "title": "Double Chance Predictions - 1X, 12, X2 Soccer Tips - Soka King",
    "displayTitle": "Double Chance (1X, 12, X2) Predictions Today",
    "description": "Secure Double Chance predictions (1X, 12, X2). Minimize risk with mathematical safety nets and multi-bet optimization slips.",
    "keywords": "double chance predictions, 1X predictions, X2 tips, double chance sure bet",
    "link": "/football-predictions-double-chance",
    "type": "category",
    "fixturesCategory": "doublechance",
    "authorId": "david-ochieng",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Gambling involves risk. Bet responsibly and stay within limits. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock Low-Variance Double Chance Slips",
    "unlockDescription": "Get safe 1X, X2, and 12 combinations calculated to protect your multi-bets against draw traps.",
    "listTitle": "Double Chance Free Predictions",
    "listSubtitle": "High-probability daily double-chance options and safety single tips verified by Soka King mathematical indexes."
  },
  "category-homewin": {
    "pageKey": "category-homewin",
    "title": "1X2 Home Win Predictions & Elite Soccer Tips - Soka King",
    "displayTitle": "1X2 Home Win Football Predictions Today",
    "description": "Premium 1X2 Home Win predictions. Home ground advantage metrics, team form ratings, and high-probability home win tips.",
    "keywords": "home win predictions, 1X2 tips today, sure home wins",
    "link": "/football-predictions-1x2-home-win",
    "type": "category",
    "fixturesCategory": "homewin",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Please gamble responsibly and keep track of your betting stakes. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock High-Probability Home Win Bankers",
    "unlockDescription": "Get high-confidence 1X2 home win selections based on stadium crowd impact and home pitch dominance.",
    "listTitle": "1X2 Home Win Free Predictions",
    "listSubtitle": "High-probability home win selections and 1X2 banker tips verified by Soka King mathematical indexes."
  },
  "category-over15": {
    "pageKey": "category-over15",
    "title": "Over 1.5 Goals Predictions & Football Betting Tips - Soka King",
    "displayTitle": "Over 1.5 Goals Football Predictions Today",
    "description": "High-probability Over 1.5 Goals football predictions. Over 80% win rate goal-line selections and daily accumulator picks.",
    "keywords": "Over 1.5 predictions, Over 1.5 goals tips, high goal predictions",
    "link": "/football-predictions-over-1-5-goals",
    "type": "category",
    "fixturesCategory": "over15",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Bet within your means. Gambling is strictly 18+. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock Safe Over 1.5 Goals Accumulators",
    "unlockDescription": "Access reliable 2+ goal line picks with over 88% historical winning probability.",
    "listTitle": "Over 1.5 Goals Free Predictions",
    "listSubtitle": "High-probability 2+ goal match selections and goal-line tips verified by Soka King mathematical indexes."
  },
  "category-over25": {
    "pageKey": "category-over25",
    "title": "Over 2.5 Goals Predictions & High-Scoring Tips - Soka King",
    "displayTitle": "Over 2.5 Goals Football Predictions Today",
    "description": "High-conversion Over 2.5 Goals football predictions. Advanced goal expectancy models identifying high-tempo attacking fixtures.",
    "keywords": "Over 2.5 predictions, Over 2.5 goals tips today, high scoring matches",
    "link": "/football-predictions-over-2-5-goals",
    "type": "category",
    "fixturesCategory": "over25",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Gambling carries financial risk. Play responsibly. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock High-Scoring Over 2.5 Goals Slips",
    "unlockDescription": "Get daily high-tempo match picks with total expected goal lines exceeding 3 goals.",
    "listTitle": "Over 2.5 Goals Free Predictions",
    "listSubtitle": "High-probability 3+ goal match selections and high-scoring tips verified by Soka King mathematical indexes."
  },
  "category-today": {
    "pageKey": "category-today",
    "title": "Today's Football Predictions & Free Betting Tips - Soka King",
    "displayTitle": "Today's Football Predictions & Sure Betting Tips",
    "description": "Get today's free football predictions, high accuracy betting tips, 1X2, Over/Under, and BTTS predictions on Soka King.",
    "keywords": "football predictions today, soccer tips today, free betting tips Kenya, 1X2 predictions, BTTS today",
    "link": "/football-predictions-today",
    "type": "category",
    "fixturesCategory": "today",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Always gamble responsibly and set strict bankroll limits. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock Today's VIP Daily 2+ & 5+ Odds Packs",
    "unlockDescription": "Receive today's mathematically validated multi-bets directly on screen and via instant SMS.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "category-tomorrow": {
    "pageKey": "category-tomorrow",
    "title": "Tomorrow's Football Predictions & Early Betting Tips - Soka King",
    "displayTitle": "Tomorrow's Football Predictions & Early Odds Tips",
    "description": "Get tomorrow's football predictions and early value betting tips. Tactical match previews, early odds analysis, and banker picks.",
    "keywords": "football predictions tomorrow, soccer tips tomorrow, early betting tips",
    "link": "/football-predictions-tomorrow",
    "type": "category",
    "fixturesCategory": "tomorrow",
    "authorId": "david-ochieng",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Bet responsibly and control your wagering budget. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock Early Value Picks for Tomorrow",
    "unlockDescription": "Lock in high odds early before market lines adjust across major bookmakers.",
    "listTitle": "Tomorrow's Free Football Predictions",
    "listSubtitle": "High-probability early double-chance options and value single tips verified by Soka King mathematical indexes."
  },
  "category-yesterday": {
    "pageKey": "category-yesterday",
    "title": "Yesterday's Football Predictions & Winning Results - Soka King",
    "displayTitle": "Yesterday's Football Predictions & Winning Results",
    "description": "Review yesterday's football predictions and scoreline accuracy on Soka King. Model calibration check and past winning tips.",
    "keywords": "football predictions yesterday, yesterday soccer results, prediction accuracy",
    "link": "/football-predictions-yesterday",
    "type": "category",
    "fixturesCategory": "yesterday",
    "authorId": "samuel-omondi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Gamble responsibly. Past performance does not guarantee future outcomes. Helpline: 0800-720-000.",
    "unlockHeading": "Verified Historical Prediction Logs",
    "unlockDescription": "Inspect past winning tickets, model accuracy benchmarks, and settled scoreline distributions.",
    "listTitle": "Yesterday's Free Football Predictions Results",
    "listSubtitle": "Verified historical match outcomes and settled predictions audited by Soka King mathematical indexes."
  },
  "cheerplex-predictions-and-tips-today": {
    "pageKey": "cheerplex-predictions-and-tips-today",
    "title": "Cheerplex Predictions and Tips Today - Free Football Picks",
    "displayTitle": "Cheerplex Predictions & Computer Tips Today",
    "description": "Daily Cheerplex predictions and soccer tips today. Soka King provides high accuracy Cheerplex computer models and daily match previews.",
    "keywords": "cheerplex predictions, cheerplex tips today, cheerplex football, sure cheerplex tips",
    "link": "/cheerplex-predictions-and-tips-today",
    "type": "competitor",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Play responsibly. Sports betting is 18+ only. Helpline: 0800-720-000.",
    "inboundTitle": "Cheerplex Alternatives & Soccer Prediction Platforms",
    "inboundHeading": "Cheerplex Alternatives & Soccer Prediction Platforms",
    "inboundDescription": "Compare Cheerplex mathematical football tips and 1X2 banker models with top soccer analytics networks.",
    "inboundSubtitle": "Compare Cheerplex mathematical football tips and 1X2 banker models with top soccer analytics networks.",
    "unlockHeading": "Unlock Automated Cheerplex Computer Tips",
    "unlockDescription": "Access daily Cheerplex computer forecasts, match probability matrices, and banker picks.",
    "listTitle": "Cheerplex Free Football Predictions Today",
    "listSubtitle": "Daily Cheerplex computer tips and match selections verified by Soka King mathematical indexes."
  },
  "contact": {
    "pageKey": "contact",
    "title": "Contact Soka King - Customer Support",
    "displayTitle": "Contact Soka King Dispatch and Support",
    "description": "Contact Soka King support in Nairobi, Kenya. Fast assistance with M-Pesa transactions, VIP slip access, and partner API inquiries.",
    "keywords": "contact Soka King, Soka King support email, WhatsApp Soka King",
    "link": "/contact-us",
    "type": "static",
    "authorId": "grace-wanjiku",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "unlockHeading": "24/7 Support Dispatch Core",
    "unlockDescription": "Reach our technical team via email, WhatsApp, or instant M-Pesa payment verification.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "home": {
    "pageKey": "home",
    "title": "SokaKing Football Predictions and Free Tips",
    "displayTitle": "Soka King Football Prediction and Free Jackpot Tips",
    "description": "Get daily free 1X2 tips, SportPesa and Betika jackpot predictions, over 2.5 goals, and VIP packs",
    "keywords": "Soka King, sokaking prediction, sokaking tips, king soka, sokakings free tips",
    "link": "/",
    "type": "home",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "unlockHeading": "Unlock SokaKing VIP Odds Packs",
    "unlockDescription": "Get instant access to 100% proven multi-bets with a guaranteed high winning probability.",
    "listTitle": "SokaKing Daily Free Football Predictions",
    "listSubtitle": "Daily free football predictions and jackpot with 1X2, BTTS, Over/Under and full jackpot coverage updated every day"
  },
  "jackpot-list": {
    "pageKey": "jackpot-list",
    "title": "Kenyan Football Jackpot Predictions 2026 - All Major Pools - Soka King",
    "displayTitle": "Kenyan Football Jackpot Predictions 2026 - All Major Pools",
    "description": "Master jackpot hub for SportPesa, Betika, Mozzart, SportyBet, betPawa, and OdiBet. Weekly and daily jackpot predictions & double-chance tips.",
    "keywords": "jackpot predictions Kenya, SportPesa jackpot tips, Betika jackpot predictions, Mozzart jackpot tips",
    "link": "/jackpot-tips",
    "type": "jackpot",
    "jackpotId": "jackpot-list",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Bet responsibly. Jackpots involve high variance; manage your stakes. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock All Major Kenyan Jackpot Slips",
    "unlockDescription": "Get complete predictions and double-chance covers for SportPesa, Betika, Mozzart, betPawa, SportyBet, and OdiBet jackpots.",
    "listTitle": "Major Kenyan Football Jackpot Pools",
    "listSubtitle": "Explore mathematically analyzed jackpot fixture slates and double-chance strategy combinations."
  },
  "liobet-predictions-and-tips": {
    "pageKey": "liobet-predictions-and-tips",
    "title": "Liobet Predictions and Tips - Mathematical Football Analysis",
    "displayTitle": "Liobet Predictions & Mathematical Soccer Tips",
    "description": "Daily Liobet predictions and football tips. Accurate Liobet mathematical predictions for 1X2, Over 2.5 goals, and double chance.",
    "keywords": "liobet predictions, liobet tips, liobet football predictions, liobet sure win",
    "link": "/liobet-predictions-and-tips",
    "type": "competitor",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Betting carries risk. Always gamble responsibly. Helpline: 0800-720-000.",
    "inboundTitle": "Liobet Alternatives & Poisson Match Simulation Portals",
    "inboundHeading": "Liobet Alternatives & Poisson Match Simulation Portals",
    "inboundDescription": "Compare Liobet match simulations and probability ratings with other football prediction engines.",
    "inboundSubtitle": "Compare Liobet match simulations and probability ratings with other football prediction engines.",
    "unlockHeading": "Unlock Liobet Mathematical Value Picks",
    "unlockDescription": "Access quantitative 1X2, Over 2.5, and double chance predictions derived from Poisson goal curves.",
    "listTitle": "Liobet Free Football Predictions",
    "listSubtitle": "Liobet mathematical predictions and soccer tips verified by Soka King mathematical indexes."
  },
  "mozzart-grand": {
    "pageKey": "mozzart-grand",
    "title": "Mozzart Grand Jackpot Predictions & Analysis (16 Games)",
    "displayTitle": "Mozzart Grand Jackpot Selections & Covers (16 Games)",
    "description": "Mozzart Grand Jackpot 16-game predictions. Fixed KES 200 Million jackpot analysis, Poisson goal modeling, and bonus tips.",
    "keywords": "Mozzart Grand Jackpot predictions, Mozzart 16 games tips, Mozzart 200 Million jackpot",
    "link": "/free-mozzart-grand-jackpot-predictions-and-analysis",
    "type": "jackpot",
    "jackpotId": "mozzart-grand",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Gamble responsibly. Restricted to adults aged 18+. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock Mozzart KES 200M Grand Jackpot Slips",
    "unlockDescription": "Access expert 16-match selections and double-chance protection for Mozzart Grand Jackpot.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "mozzart-super-daily": {
    "pageKey": "mozzart-super-daily",
    "title": "Mozzart Super Daily Jackpot Predictions & Match Analysis",
    "displayTitle": "Mozzart Super Daily Jackpot Selections",
    "description": "Mozzart Super Daily Jackpot predictions and 16-match computer simulations. Get daily updated expert picks.",
    "keywords": "Mozzart Super Daily Jackpot predictions, Mozzart daily tips, Mozzart 16 matches",
    "link": "/free-mozzart-super-daily-jackpot-predictions-and-analysis",
    "type": "jackpot",
    "jackpotId": "mozzart-super-daily",
    "authorId": "samuel-omondi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Betting involves risk. Always gamble within your financial comfort zone. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock Mozzart Super Daily Selections",
    "unlockDescription": "Get daily computer-simulated 16-game prediction tickets for Mozzart Super Daily.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "mozzart-super-grand-2026": {
    "pageKey": "mozzart-super-grand-2026",
    "title": "Mozzart Super Grand Jackpot Predictions 2026 (20 Games)",
    "displayTitle": "Mozzart Super Grand Jackpot 20 Games Comprehensive Analysis",
    "description": "Expert predictions for the Mozzart Super Grand Jackpot 20 fixtures. Win the 200 Million jackpot with Soka King mathematical tips.",
    "keywords": "mozzart super grand jackpot, mozzart jackpot predictions 2026, 20 games jackpot",
    "link": "/mozzart-super-grand-2026",
    "type": "jackpot",
    "jackpotId": "mozzart-super-grand",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "unlockHeading": "Mozzart Super Grand Jackpot 20 Games Comprehensive Analysis",
    "unlockDescription": "Expert predictions for the Mozzart Super Grand Jackpot 20 fixtures. Win the 200 Million jackpot with Soka King mathematical tips.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "odibet-laki-tatu": {
    "pageKey": "odibet-laki-tatu",
    "title": "OdiBet Laki Tatu Jackpot Predictions & Daily Tips",
    "displayTitle": "OdiBet Laki Tatu Jackpot Selections (10 Games)",
    "description": "OdiBet Laki Tatu daily jackpot predictions for 10 games. KES 300,000 cash prize analysis for KES 15 stake.",
    "keywords": "OdiBet Laki Tatu predictions, OdiBet daily jackpot tips, OdiBet 10 games",
    "link": "/free-odibet-laki-tatu-jackpot-predictions-and-analysis",
    "type": "jackpot",
    "jackpotId": "odibet-laki-tatu",
    "authorId": "grace-wanjiku",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Play responsibly. 18+ only. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock OdiBet Laki Tatu Jackpot Predictions",
    "unlockDescription": "Get daily 10-game jackpot predictions for OdiBet's KES 300,000 cash pool.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "partners": {
    "pageKey": "partners",
    "title": "Our Strategic Partners - Soka King",
    "displayTitle": "Our Strategic Partners",
    "description": "Soka King partners with supporters and moajor prediction sites",
    "keywords": "Soka King partners",
    "link": "/partners",
    "type": "static",
    "authorId": "samuel-omondi",
    "authorName": "Dr. Samuel Omondi",
    "authorTitle": "Chief Data Scientist",
    "unlockHeading": "Soka King Partner Ecosystem",
    "unlockDescription": "Learn about our partners",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "predictz-predictions": {
    "pageKey": "predictz-predictions",
    "title": "PredictZ Predictions Today & Mathematical Football Tips",
    "displayTitle": "PredictZ Accurate Football Predictions & Soka King Tips",
    "description": "Looking for PredictZ football predictions today? Get free Poisson distribution banker tips, over 2.5 goals, and double chance predictions.",
    "keywords": "predictz predictions, predictz today, predictz tips, predictz football",
    "link": "/predictz-predictions",
    "type": "competitor",
    "icon": "⚽",
    "badgeColor": "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "inboundTitle": "PredictZ Alternatives & Goal Modeling Portals",
    "inboundHeading": "PredictZ Alternatives & Goal Modeling Portals",
    "inboundDescription": "Compare PredictZ goal distribution models and 1X2 rating simulations with top verified soccer prediction networks.",
    "inboundSubtitle": "Compare PredictZ goal distribution models and 1X2 rating simulations with top verified soccer prediction networks.",
    "unlockHeading": "PredictZ Accurate Football Predictions & Soka King Tips",
    "unlockDescription": "Looking for PredictZ football predictions today? Get free Poisson distribution banker tips, over 2.5 goals, and double chance predictions.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "privacy-policy": {
    "pageKey": "privacy-policy",
    "title": "Privacy Policy and Data Security - Soka King",
    "displayTitle": "Privacy Policy and Data Protection Protocols",
    "description": "Privacy policy for Soka King. Learn how we protect user data and comply with Kenya Data Protection Act 2019.",
    "keywords": "privacy policy Soka King, data protection Kenya, M-Pesa privacy",
    "link": "/privacy-policy",
    "type": "static",
    "authorId": "legal-compliance",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "unlockHeading": "Data Privacy and Security",
    "unlockDescription": "Review how we safeguard user data.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "responsible-gambling": {
    "pageKey": "responsible-gambling",
    "title": "Responsible Gambling & Player Protection - Soka King",
    "displayTitle": "Responsible Gambling & Player Protection Center",
    "description": "Soka King advocates for responsible gambling, strict 18+ age limits, and healthy bankroll management.",
    "keywords": "responsible gambling Kenya, player protection, betting helpline",
    "link": "/responsible-gambling",
    "type": "static",
    "authorId": "soka-safety-board",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "If gambling is affecting your life, call the national helpline: 0800-720-000.",
    "unlockHeading": "Safe Gaming & Bankroll Protection",
    "unlockDescription": "Learn about bankroll allocation rules, loss control, and self-exclusion tools.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "soccervista-predictions-and-tips": {
    "pageKey": "soccervista-predictions-and-tips",
    "title": "SoccerVista Predictions & Free Daily Football Tips 2026",
    "displayTitle": "SoccerVista Predictions & Mathematical Soccer Tips",
    "description": "Looking for SoccerVista predictions? Get superior Soka King mathematical football predictions, 1X2 banker tips, and Poisson goal distribution forecasts.",
    "keywords": "soccervista predictions, soccervista tips, soccervista football tips, soccervista alternative",
    "link": "/soccervista-predictions-and-tips",
    "type": "competitor",
    "icon": "🌐",
    "badgeColor": "bg-purple-500/10 text-purple-500 border-purple-500/20",
    "authorId": "david-ochieng",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "inboundTitle": "SoccerVista Alternatives & Statistical Tip Portals",
    "inboundHeading": "SoccerVista Alternatives & Statistical Tip Portals",
    "inboundDescription": "Explore football analysis engines and mathematical prediction sites alongside SoccerVista head-to-head metrics.",
    "inboundSubtitle": "Explore football analysis engines and mathematical prediction sites alongside SoccerVista head-to-head metrics.",
    "unlockHeading": "Unlock VIP SoccerVista-Style Banker Accumulators",
    "unlockDescription": "Activate VIP predictions with instant M-Pesa push confirmation for premium 2.00+ odds.",
    "listTitle": "SoccerVista Free Football Predictions Today",
    "listSubtitle": "Daily SoccerVista style match selections and 1X2 banker tips verified by Soka King mathematical indexes."
  },
  "sokamastas-predictions-and-tips": {
    "pageKey": "sokamastas-predictions-and-tips",
    "title": "Sokamastas Predictions and Today Tips",
    "displayTitle": "Sokamastas Predictions and Today Tips",
    "description": "Looking for Sokamastas predictions? Get them here. We Sokamastas tips ready for yoo with, 1X2 banker tips, and Poisson goal distribution forecasts.",
    "keywords": "sokamasta, Sokamasta, sokamastas, Sokamastas,soka masters tips",
    "link": "/sokamastas-predictions-and-tips",
    "type": "competitor",
    "icon": "🌐",
    "badgeColor": "bg-purple-500/10 text-purple-500 border-purple-500/20",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "inboundTitle": "Alternative Prediction to Sokamastas Tips",
    "inboundHeading": "Alternative Prediction to Sokamastas Tips",
    "inboundDescription": "Compare and contrast sokaking and Sokamastas Altenatives.",
    "inboundSubtitle": "Compare and contrast sokaking and Sokamastas Altenatives.",
    "unlockHeading": "Get Sharper, Not Just Luckier",
    "unlockDescription": "Activate VIP predictions and Get Premium Soka Masterd Tips.",
    "listTitle": "Today Sokamasta Free Football Tips",
    "listSubtitle": "Daily Sokamastas match selections verified by Soka King indexes and Analyst."
  },
  "sportpesa-mega-jackpot-2026": {
    "pageKey": "sportpesa-mega-jackpot-2026",
    "title": "SportPesa Mega Jackpot Predictions 2026 (17 Games Analysis)",
    "displayTitle": "SportPesa Mega Jackpot 17 Games Comprehensive 2026 Predictions",
    "description": "Expert mathematical analysis and double chance predictions for the 2026 SportPesa Mega Jackpot 17 fixtures. Win bonuses with Soka King models.",
    "keywords": "sportpesa mega jackpot predictions 2026, sportpesa mega jackpot 17 games, mega jackpot analysis 2026",
    "link": "/sportpesa-mega-jackpot-2026",
    "type": "jackpot",
    "jackpotId": "sportpesa-mega",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "unlockHeading": "SportPesa Mega Jackpot 17 Games Comprehensive 2026 Predictions",
    "unlockDescription": "Expert mathematical analysis and double chance predictions for the 2026 SportPesa Mega Jackpot 17 fixtures. Win bonuses with Soka King models.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "sportpesa-mega": {
    "pageKey": "sportpesa-mega",
    "title": "SportPesa Mega Jackpot Predictions & KES 300 Million Analysis (17 Games)",
    "displayTitle": "SportPesa Mega Jackpot Selections & Covers (17 Games)",
    "description": "Expert SportPesa Mega Jackpot predictions, 17-game ticket analysis, and double chance combinations for Kenya's KES 300M+ jackpot pool.",
    "keywords": "SportPesa Mega Jackpot predictions, SportPesa tips today, 17 games jackpot Kenya, SportPesa bonus tips",
    "link": "/free-sportpesa-mega-jackpot-predictions-and-analysis",
    "type": "jackpot",
    "jackpotId": "sportpesa-mega",
    "authorId": "john-mwangi",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Gambling involves risk. Bet responsibly and only risk what you can afford. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock All 17 SportPesa Mega Jackpot Predictions",
    "unlockDescription": "Subscribe to get instant access to full 1X2 selections, banker probability rankings, and low-variance double-chance covers for SportPesa Mega Jackpot.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "sportpesa-midweek": {
    "pageKey": "sportpesa-midweek",
    "title": "SportPesa Midweek Jackpot Predictions & Daily Tips (13 Games)",
    "displayTitle": "SportPesa Midweek Jackpot Selections & Covers (13 Games)",
    "description": "Accurate SportPesa Midweek Jackpot predictions for all 13 matches. Get computer models and double chance tips for KES 10M+ prizes.",
    "keywords": "SportPesa Midweek Jackpot, SportPesa 13 games predictions, Midweek Jackpot tips, SportPesa double chance",
    "link": "/free-sportpesa-midweek-jackpot-predictions-and-analysis",
    "type": "jackpot",
    "jackpotId": "sportpesa-midweek",
    "authorId": "david-ochieng",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Bet responsibly. Always play within your budget. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock SportPesa Midweek Jackpot Predictions",
    "unlockDescription": "Access 13-match selections, midweek fatigue matrix analysis, and double-chance covers for SportPesa Midweek Jackpot.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "sportybet-jackpot": {
    "pageKey": "sportybet-jackpot",
    "title": "SportyBet Jackpot Predictions & Master Ticket Analysis",
    "displayTitle": "SportyBet Weekly Jackpot Selections & Master Ticket",
    "description": "SportyBet weekly jackpot predictions and master ticket analysis. Poisson probability and team metrics for SportyBet jackpot.",
    "keywords": "SportyBet jackpot predictions, SportyBet tips, SportyBet 12 games jackpot",
    "link": "/free-sportybet-jackpot-predictions-and-analysis",
    "type": "jackpot",
    "jackpotId": "sportybet-jackpot",
    "authorId": "grace-wanjiku",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Play responsibly and observe betting limits. Helpline: 0800-720-000.",
    "unlockHeading": "Unlock SportyBet Jackpot Master Ticket",
    "unlockDescription": "Get 12-game weekly jackpot predictions optimized for SportyBet Kenya and Nigeria.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "sunpel-free-football-betting-tips": {
    "pageKey": "sunpel-free-football-betting-tips",
    "title": "Sunpelpredict | Sunpel Free Football Betting Tips & Predictions Today",
    "displayTitle": "Sunpelpredict - Free Football Betting Tips & Soccer Predictions Today",
    "description": "Get free Sunpelpredict football betting tips and accurate Sunpel soccer predictions today. Access daily banker picks, 1X2 tips, over 2.5 goals, and jackpot predictions.",
    "keywords": "sunpelpredict, sunpel predict, sunpel predictions, sunpel football tips, sunpelpredict today, sunpel free betting tips, sunpel soccer, sunpel banker tips, sunpel tips today",
    "link": "/sunpel-free-football-betting-tips-and-soccer-predictions",
    "type": "competitor",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "responsibleGambling": "Betting is strictly 18+. Please gamble responsibly. Helpline: 0800-720-000.",
    "inboundTitle": "Sunpel Alternatives & Free Football Prediction Networks",
    "inboundHeading": "Sunpel Alternatives & Free Football Prediction Networks",
    "inboundDescription": "Compare Sunpel banker picks and soccer analysis with other verified mathematical tipsters and daily prediction models.",
    "inboundSubtitle": "Compare Sunpel banker picks and soccer analysis with other verified mathematical tipsters and daily prediction models.",
    "unlockHeading": "Unlock Daily Sunpelpredict Banker Picks",
    "unlockDescription": "Access daily Sunpelpredict banker selections, high-value goal-line tips, and weekend accumulator slips.",
    "listTitle": "Sunpelpredict Free Football Predictions Today",
    "listSubtitle": "Daily Sunpel banker selections, double chance picks, and mathematical soccer tips verified by Soka King."
  },
  "terms-of-use": {
    "pageKey": "terms-of-use",
    "title": "Terms of Use andSubscription Agreement - Soka King",
    "displayTitle": "Terms of Use and Digital Service Agreement",
    "description": "Terms of use governing access to Soka King's football predictions and VIP jackpots.",
    "keywords": "terms of use Soka King",
    "link": "/terms-of-use",
    "type": "static",
    "authorId": "legal-compliance",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst & Poisson Modeler",
    "unlockHeading": "Terms of Service andVIP Access",
    "unlockDescription": "Understand subscription rules, digital key delivery via M-Pesa, and usage guidelines.",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  },
  "vip-packages": {
    "pageKey": "vip-packages",
    "title": "Soka King VIP Packages, Premium Odds and Jackpot Predictions",
    "displayTitle": "VIP Packages, Daily Odds Packs and VIP Jackpot",
    "description": "Upgrade to Soka King VIP subscription packages. We have daily 2+ and 5+ odds. Do not miss all jackpot prediction slips available every day.",
    "keywords": "Soka King VIP, VIP betting tips, Kenya VIP football predictions",
    "link": "/vip-packages",
    "authorId": "brian-kipchumba",
    "authorName": "John K. Mwangi",
    "authorTitle": "Lead Football Analyst and Poisson Model Expert",
    "unlockHeading": "Unlock Soka King VIP Packages and Daily Odds Slips",
    "unlockDescription": "Upgrade to receive 2+ odds, 5+ odds  and all jackpot",
    "listTitle": "Today's Free Football Predictions",
    "listSubtitle": "High-probability daily double-chance options and standard single tips verified by Soka King mathematical indexes."
  }
};
