import { Fixture } from './types';
import { applyDynamicKenyanSchedule } from './utils/jackpotSchedule';

export interface JackpotConfig {
  id: string;
  name: string;
  slug: string;
  gamesCount: number;
  price: number;
  entryFee: string;
  estimatedPool: string;
  nextGameStartTime: string;
  submissionsFill: string;
  premiumCount: string;
  fixtures: Fixture[];
}

const rawJackpotsData: JackpotConfig[] = [
  {
    id: 'sportpesa-mega',
    name: 'SportPesa Mega Jackpot',
    slug: 'sportpesa-mega',
    gamesCount: 17,
    price: 1,
    entryFee: 'KES 99',
    estimatedPool: 'KES 385,400,000',
    nextGameStartTime: 'Starts Saturday: 16:30 EAT (Nairobi)',
    submissionsFill: '94%',
    premiumCount: '12,450+',
    fixtures: [
      {
        id: 1,
        fixtureNumber: 1,
        homeTeam: 'Manchester United',
        awayTeam: 'Chelsea',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T15:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: 2,
        awayScore: 2,
        confidence: 84,
        aiAnalysis: 'High stakes EPL clash. Tactical setups lean heavily on cautious double pivots. Home ground advantage favors a draw or home win.'
      },
      {
        id: 2,
        fixtureNumber: 2,
        homeTeam: 'Bournemouth',
        awayTeam: 'Newcastle',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T14:30:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: 0,
        awayScore: 0,
        confidence: 76,
        aiAnalysis: 'Both sides average below 1.5 expected goals per game. Low block strategies are expected.'
      },
      {
        id: 3,
        fixtureNumber: 3,
        homeTeam: 'Albacete',
        awayTeam: 'Valladolid',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T16:00:00Z',
        leagueName: 'Segunda División',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        homeScore: 2,
        awayScore: 2,
        confidence: 71,
        aiAnalysis: 'Valladolid holds superior squad depth and tactical transition metrics over Albacete.'
      },
      {
        id: 4,
        fixtureNumber: 4,
        homeTeam: 'Tondela',
        awayTeam: 'Estrela',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T18:00:00Z',
        leagueName: 'Primeira Liga',
        leagueFlag: '🇵🇹',
        countryName: 'Portugal',
        homeScore: 0,
        awayScore: 0,
        confidence: 68,
        aiAnalysis: 'Estrela is currently in stable defensive shape. Tondela is struggling with offensive conversions.'
      },
      {
        id: 5,
        fixtureNumber: 5,
        homeTeam: 'AZ Alkmaar',
        awayTeam: 'Feyenoord',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T13:30:00Z',
        leagueName: 'Eredivisie',
        leagueFlag: '🇳🇱',
        countryName: 'Netherlands',
        homeScore: 3,
        awayScore: 3,
        confidence: 78,
        aiAnalysis: 'Feyenoord has a strong offensive dynamic away record, averaging 2.2 goals per game.'
      },
      {
        id: 6,
        fixtureNumber: 6,
        homeTeam: 'Stromsgodset',
        awayTeam: 'Sarpsborg 08 FF',
        prediction: 'Double Chance (12)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T15:00:00Z',
        leagueName: 'Eliteserien',
        leagueFlag: '🇳🇴',
        countryName: 'Norway',
        homeScore: 2,
        awayScore: 2,
        confidence: 72,
        aiAnalysis: 'Fierce battle with open channels. Minimal midfield stagnation points towards a decisive outcome.'
      },
      {
        id: 7,
        fixtureNumber: 7,
        homeTeam: 'Auxerre',
        awayTeam: 'Toulouse',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T14:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 1,
        awayScore: 1,
        confidence: 69,
        aiAnalysis: 'Toulouse compact defense minimizes wide threats. High probability of a low-scoring draw or away steal.'
      },
      {
        id: 8,
        fixtureNumber: 8,
        homeTeam: 'Le Havre',
        awayTeam: 'Lorient',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T14:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 1,
        awayScore: 1,
        confidence: 73,
        aiAnalysis: 'Le Havre holds a strong defensive record at home. Lorient shows vulnerabilities on counter-attacks.'
      },
      {
        id: 9,
        fixtureNumber: 9,
        homeTeam: 'Fiorentina',
        awayTeam: 'Como',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T11:30:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: 1,
        awayScore: 1,
        confidence: 81,
        aiAnalysis: 'Fiorentina dominates possession metrics in Tuscany. Como is struggling to find a stable defensive block.'
      },
      {
        id: 10,
        fixtureNumber: 10,
        homeTeam: 'Aarhus',
        awayTeam: 'Brondby',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T17:00:00Z',
        leagueName: 'Superliga',
        leagueFlag: '🇩🇰',
        countryName: 'Denmark',
        homeScore: 1,
        awayScore: 1,
        confidence: 74,
        aiAnalysis: 'Brondby dynamic front three are expected to penetrate Aarhus low-block setup successfully.'
      },
      {
        id: 11,
        fixtureNumber: 11,
        homeTeam: 'Malaga',
        awayTeam: 'Cadiz',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T15:15:00Z',
        leagueName: 'Segunda División',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        homeScore: 0,
        awayScore: 0,
        confidence: 70,
        aiAnalysis: 'Cadiz holds the tactical advantage with experienced pivots who dictate transition tempo.'
      },
      {
        id: 12,
        fixtureNumber: 12,
        homeTeam: 'Elche',
        awayTeam: 'Oviedo',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T17:30:00Z',
        leagueName: 'La Liga',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        homeScore: 1,
        awayScore: 1,
        confidence: 75,
        aiAnalysis: 'Elche boasts clean-sheet parameters at home. Oviedo shows modest away conversion numbers.'
      },
      {
        id: 13,
        fixtureNumber: 13,
        homeTeam: 'GIL Vicente',
        awayTeam: 'Estoril',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T14:30:00Z',
        leagueName: 'Primeira Liga',
        leagueFlag: '🇵🇹',
        countryName: 'Portugal',
        homeScore: 2,
        awayScore: 2,
        confidence: 77,
        aiAnalysis: 'Gil Vicente is dominant in second-half duels. Estoril struggles away with high fatigue indexes.'
      },
      {
        id: 14,
        fixtureNumber: 14,
        homeTeam: 'KV Mechelen',
        awayTeam: 'Cercle Brugge',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T15:00:00Z',
        leagueName: 'Jupiler Pro League',
        leagueFlag: '🇧🇪',
        countryName: 'Belgium',
        homeScore: 0,
        awayScore: 0,
        confidence: 74,
        aiAnalysis: 'Mechelen maintains strong home defensive structures. Cercle Brugge struggles to contain set plays.'
      },
      {
        id: 15,
        fixtureNumber: 15,
        homeTeam: 'Padova',
        awayTeam: 'Virtus Entella',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T19:45:00Z',
        leagueName: 'Serie B',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: 2,
        awayScore: 2,
        confidence: 65,
        aiAnalysis: 'Entella exhibits superior transitional speed which should exploit Padova defensive lines.'
      },
      {
        id: 16,
        fixtureNumber: 16,
        homeTeam: 'Panathinaikos',
        awayTeam: 'Olympiakos Piraeus',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T18:30:00Z',
        leagueName: 'Super League 1',
        leagueFlag: '🇬🇷',
        countryName: 'Greece',
        homeScore: 1,
        awayScore: 1,
        confidence: 79,
        aiAnalysis: 'Eternal enemies derby. Olympiakos has superior offensive metrics and high physical dominance.'
      },
      {
        id: 17,
        fixtureNumber: 17,
        homeTeam: 'Cordoba',
        awayTeam: 'Racing Santander',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T20:00:00Z',
        leagueName: 'Segunda División',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        homeScore: 2,
        awayScore: 2,
        confidence: 70,
        aiAnalysis: 'Santander currently leads in transition and shot creation metrics. High probability of away win.'
      }
    ]
  },
  {
    id: 'betika-midweek',
    name: 'Betika Midweek Jackpot',
    slug: 'betika-midweek',
    gamesCount: 15,
    price: 5,
    entryFee: 'KES 15',
    estimatedPool: 'KES 15,000,000',
    nextGameStartTime: 'Starts Saturday: 13:30 EAT (Nairobi)',
    submissionsFill: '89%',
    premiumCount: '7,120+',
    fixtures: [
      {
        id: 101,
        fixtureNumber: 1,
        homeTeam: 'FC St. Pauli',
        awayTeam: 'Bayer Leverkusen',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T13:30:00Z',
        leagueName: 'Bundesliga',
        leagueFlag: '🇩🇪',
        countryName: 'Germany',
        homeScore: '-',
        awayScore: '-',
        confidence: 88,
        aiAnalysis: 'Leverkusen displays exceptional transition indices under Alonso. St. Pauli faces a tough tactical block.'
      },
      {
        id: 102,
        fixtureNumber: 2,
        homeTeam: 'VfL Wolfsburg',
        awayTeam: 'RB Leipzig',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T13:30:00Z',
        leagueName: 'Bundesliga',
        leagueFlag: '🇩🇪',
        countryName: 'Germany',
        homeScore: '-',
        awayScore: '-',
        confidence: 77,
        aiAnalysis: 'Leipzig dominant tactical shape and front-line efficiency should comfortably breach Wolfsburg high-line.'
      },
      {
        id: 103,
        fixtureNumber: 3,
        homeTeam: 'FSV Mainz 05',
        awayTeam: 'Borussia Dortmund',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T13:30:00Z',
        leagueName: 'Bundesliga',
        leagueFlag: '🇩🇪',
        countryName: 'Germany',
        homeScore: '-',
        awayScore: '-',
        confidence: 74,
        aiAnalysis: 'Dortmund holds clinical finishing advantages over Mainz. Expected offensive domination.'
      },
      {
        id: 104,
        fixtureNumber: 4,
        homeTeam: '1. FC Heidenheim',
        awayTeam: 'FC Augsburg',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T13:30:00Z',
        leagueName: 'Bundesliga',
        leagueFlag: '🇩🇪',
        countryName: 'Germany',
        homeScore: '-',
        awayScore: '-',
        confidence: 69,
        aiAnalysis: 'Augsburg features higher conversion metrics inside the box compared to Heidenheim defensive structures.'
      },
      {
        id: 105,
        fixtureNumber: 5,
        homeTeam: 'Leeds',
        awayTeam: 'Bournemouth',
        prediction: 'Double Chance (12)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T15:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: '-',
        awayScore: '-',
        confidence: 72,
        aiAnalysis: 'An open aggressive contest with high transition metrics. Decisive game unlikely to result in a draw.'
      },
      {
        id: 106,
        fixtureNumber: 6,
        homeTeam: 'Sassuolo',
        awayTeam: 'Udinese',
        prediction: 'Draw (X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T13:00:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: '-',
        awayScore: '-',
        confidence: 66,
        aiAnalysis: 'Historically tight meeting. Midfield-dominated low risk structures from both managers point towards a draw.'
      },
      {
        id: 107,
        fixtureNumber: 7,
        homeTeam: 'Pisa',
        awayTeam: 'Fiorentina',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T13:00:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: '-',
        awayScore: '-',
        confidence: 82,
        aiAnalysis: 'Fiorentina contains superior team coherence and squad depths to dominate this Tuscan derby.'
      },
      {
        id: 108,
        fixtureNumber: 8,
        homeTeam: 'SC Freiburg',
        awayTeam: '1899 Hoffenheim',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T14:30:00Z',
        leagueName: 'Bundesliga',
        leagueFlag: '🇩🇪',
        countryName: 'Germany',
        homeScore: '-',
        awayScore: '-',
        confidence: 78,
        aiAnalysis: 'Freiburg is incredibly structured in home defenses, keeping high pressure limits against Hoffenheim.'
      },
      {
        id: 109,
        fixtureNumber: 9,
        homeTeam: 'Metz',
        awayTeam: 'Le Havre',
        prediction: 'Double Chance (X1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T15:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: '-',
        awayScore: '-',
        confidence: 70,
        aiAnalysis: 'Metz home ground protection index remains extremely stable. Le Havre struggles outside home.'
      },
      {
        id: 110,
        fixtureNumber: 10,
        homeTeam: 'Lille',
        awayTeam: 'Lyon',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T15:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: '-',
        awayScore: '-',
        confidence: 71,
        aiAnalysis: 'Lyon possesses superior offensive indices in open spaces which should dissect Lille high defensive line.'
      },
      {
        id: 111,
        fixtureNumber: 11,
        homeTeam: 'Angers',
        awayTeam: 'Stade Brestois 29',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T15:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: '-',
        awayScore: '-',
        confidence: 79,
        aiAnalysis: 'Stade Brestois shows brilliant physical structures in midfield which should overwhelm Angers pivots.'
      },
      {
        id: 112,
        fixtureNumber: 12,
        homeTeam: '1.FC Köln',
        awayTeam: 'VfB Stuttgart',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T15:30:00Z',
        leagueName: 'Bundesliga',
        leagueFlag: '🇩🇪',
        countryName: 'Germany',
        homeScore: '-',
        awayScore: '-',
        confidence: 83,
        aiAnalysis: 'Stuttgart fast transitional wingplay is expected to comfortably overwhelm Köln wings.'
      },
      {
        id: 113,
        fixtureNumber: 13,
        homeTeam: 'Newcastle',
        awayTeam: 'Arsenal',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T16:30:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: '-',
        awayScore: '-',
        confidence: 80,
        aiAnalysis: 'Arsenal boasts superior clean-sheet indicators. High tactical control makes a defeat unlikely.'
      },
      {
        id: 114,
        fixtureNumber: 14,
        homeTeam: 'AC Milan',
        awayTeam: 'Napoli',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T18:45:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: '-',
        awayScore: '-',
        confidence: 76,
        aiAnalysis: 'Napoli boasts incredible defensive form under their low-block structured setup. Ideal counter-attacking threat.'
      },
      {
        id: 115,
        fixtureNumber: 15,
        homeTeam: 'Rennes',
        awayTeam: 'Lens',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T19:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: '-',
        awayScore: '-',
        confidence: 74,
        aiAnalysis: 'Lens stable pivots and high-pressure system are expected to contain Rennes wide options.'
      }
    ]
  },
  {
    id: 'mozzart-grand',
    name: 'Mozzart Grand Jackpot',
    slug: 'mozzart-grand',
    gamesCount: 20,
    price: 700,
    entryFee: 'KES 50',
    estimatedPool: 'KES 200,000,000',
    nextGameStartTime: 'Starts Sunday: 10:30 EAT (Nairobi)',
    submissionsFill: '81%',
    premiumCount: '4,890+',
    fixtures: [
      {
        id: 201,
        fixtureNumber: 1,
        homeTeam: 'Bournemouth',
        awayTeam: 'Newcastle',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T14:30:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 72
      },
      {
        id: 202,
        fixtureNumber: 2,
        homeTeam: 'Brighton',
        awayTeam: 'Tottenham',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T16:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 75
      },
      {
        id: 203,
        fixtureNumber: 3,
        homeTeam: 'Burnley',
        awayTeam: 'Nottingham Forest',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T15:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 68
      },
      {
        id: 204,
        fixtureNumber: 4,
        homeTeam: 'West Ham',
        awayTeam: 'Crystal Palace',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T15:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 71
      },
      {
        id: 205,
        fixtureNumber: 5,
        homeTeam: 'Wolves',
        awayTeam: 'Leeds',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T15:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 74
      },
      {
        id: 206,
        fixtureNumber: 6,
        homeTeam: 'Derby',
        awayTeam: 'Preston',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T15:00:00Z',
        leagueName: 'Championship',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 69
      },
      {
        id: 207,
        fixtureNumber: 7,
        homeTeam: 'Hull City',
        awayTeam: 'Southampton',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T15:00:00Z',
        leagueName: 'Championship',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 73
      },
      {
        id: 208,
        fixtureNumber: 8,
        homeTeam: 'Manchester United',
        awayTeam: 'Chelsea',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T15:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 80
      },
      {
        id: 209,
        fixtureNumber: 9,
        homeTeam: 'Alaves',
        awayTeam: 'Sevilla',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T18:30:00Z',
        leagueName: 'La Liga',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        confidence: 75
      },
      {
        id: 210,
        fixtureNumber: 10,
        homeTeam: 'Stade Brestois 29',
        awayTeam: 'Nice',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T19:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        confidence: 72
      },
      {
        id: 211,
        fixtureNumber: 11,
        homeTeam: 'Valencia',
        awayTeam: 'Athletic Club',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T17:30:00Z',
        leagueName: 'La Liga',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        confidence: 79
      },
      {
        id: 212,
        fixtureNumber: 12,
        homeTeam: 'Lens',
        awayTeam: 'Lille',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-20T20:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        confidence: 78
      },
      {
        id: 213,
        fixtureNumber: 13,
        homeTeam: 'Lazio',
        awayTeam: 'AS Roma',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T16:00:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        confidence: 81
      },
      {
        id: 214,
        fixtureNumber: 14,
        homeTeam: 'Rayo Vallecano',
        awayTeam: 'Celta Vigo',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T12:00:00Z',
        leagueName: 'La Liga',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        confidence: 73
      },
      {
        id: 215,
        fixtureNumber: 15,
        homeTeam: 'Sunderland',
        awayTeam: 'Aston Villa',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T13:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 85
      },
      {
        id: 216,
        fixtureNumber: 16,
        homeTeam: 'Cremonese',
        awayTeam: 'Parma',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T14:00:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        confidence: 67
      },
      {
        id: 217,
        fixtureNumber: 17,
        homeTeam: 'Paris FC',
        awayTeam: 'Strasbourg',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T15:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        confidence: 72
      },
      {
        id: 218,
        fixtureNumber: 18,
        homeTeam: 'Auxerre',
        awayTeam: 'Toulouse',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T14:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        confidence: 69
      },
      {
        id: 219,
        fixtureNumber: 19,
        homeTeam: 'Le Havre',
        awayTeam: 'Lorient',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T14:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        confidence: 74
      },
      {
        id: 220,
        fixtureNumber: 20,
        homeTeam: 'Fiorentina',
        awayTeam: 'Como',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-21T11:30:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        confidence: 82
      }
    ]
  },
  {
    id: 'sportpesa-midweek',
    name: 'SportPesa Midweek',
    slug: 'sportpesa-midweek',
    gamesCount: 13,
    price: 1,
    entryFee: 'KES 99',
    estimatedPool: 'KES 15,800,000',
    nextGameStartTime: 'Starts Wednesday: 17:00 EAT (Nairobi)',
    submissionsFill: '92%',
    premiumCount: '8,210+',
    fixtures: [
      {
        id: 301,
        fixtureNumber: 1,
        homeTeam: 'Goztepe',
        awayTeam: 'Besiktas',
        prediction: 'Double Chance (X2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T17:00:00Z',
        leagueName: 'Süper Lig',
        leagueFlag: '🇹🇷',
        countryName: 'Turkey',
        homeScore: 3,
        awayScore: 3,
        confidence: 83
      },
      {
        id: 302,
        fixtureNumber: 2,
        homeTeam: 'Frosinone',
        awayTeam: 'Sudtirol',
        prediction: 'Double Chance (X2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:30:00Z',
        leagueName: 'Serie B',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: 2,
        awayScore: 2,
        confidence: 76
      },
      {
        id: 303,
        fixtureNumber: 3,
        homeTeam: 'Concarneau',
        awayTeam: 'Fleury 91',
        prediction: 'Home Win (1)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:00:00Z',
        leagueName: 'National 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 0,
        awayScore: 0,
        confidence: 71
      },
      {
        id: 304,
        fixtureNumber: 4,
        homeTeam: 'Rouen',
        awayTeam: 'Orleans',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:00:00Z',
        leagueName: 'National 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 1,
        awayScore: 1,
        confidence: 72
      },
      {
        id: 305,
        fixtureNumber: 5,
        homeTeam: 'Stade Briochin',
        awayTeam: 'Le Puy Foot',
        prediction: 'Double Chance (X2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:00:00Z',
        leagueName: 'National 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 1,
        awayScore: 1,
        confidence: 68
      },
      {
        id: 306,
        fixtureNumber: 6,
        homeTeam: 'Aubagne',
        awayTeam: 'Versailles',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:00:00Z',
        leagueName: 'National 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 1,
        awayScore: 1,
        confidence: 73
      },
      {
        id: 307,
        fixtureNumber: 7,
        homeTeam: 'Sparta Rotterdam',
        awayTeam: 'Twente',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:00:00Z',
        leagueName: 'Eredivisie',
        leagueFlag: '🇳🇱',
        countryName: 'Netherlands',
        homeScore: 1,
        awayScore: 1,
        confidence: 78
      },
      {
        id: 308,
        fixtureNumber: 8,
        homeTeam: 'Nancy',
        awayTeam: 'RED Star FC 93',
        prediction: 'Double Chance (X2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:30:00Z',
        leagueName: 'Ligue 2',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 0,
        awayScore: 0,
        confidence: 74
      },
      {
        id: 309,
        fixtureNumber: 9,
        homeTeam: 'Emmen',
        awayTeam: 'Dordrecht',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:00:00Z',
        leagueName: 'Eerste Divisie',
        leagueFlag: '🇳🇱',
        countryName: 'Netherlands',
        homeScore: 2,
        awayScore: 2,
        confidence: 80
      },
      {
        id: 310,
        fixtureNumber: 10,
        homeTeam: 'Wisla Plock',
        awayTeam: 'Jagiellonia',
        prediction: 'Home Win (1)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:30:00Z',
        leagueName: 'Ekstraklasa',
        leagueFlag: '🇵🇱',
        countryName: 'Poland',
        homeScore: 0,
        awayScore: 0,
        confidence: 71
      },
      {
        id: 311,
        fixtureNumber: 11,
        homeTeam: 'Kilmarnock',
        awayTeam: 'ST Mirren',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:45:00Z',
        leagueName: 'League Cup',
        leagueFlag: '🇬🇧',
        countryName: 'Scotland',
        homeScore: 2,
        awayScore: 2,
        confidence: 79
      },
      {
        id: 312,
        fixtureNumber: 12,
        homeTeam: 'Lecce',
        awayTeam: 'Cagliari',
        prediction: 'Double Chance (X1)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:45:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: 1,
        awayScore: 1,
        confidence: 75
      },
      {
        id: 313,
        fixtureNumber: 13,
        homeTeam: 'Sligo Rovers',
        awayTeam: 'Drogheda United',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-19T18:45:00Z',
        leagueName: 'Premier Division',
        leagueFlag: '🇮🇪',
        countryName: 'Ireland',
        homeScore: 1,
        awayScore: 1,
        confidence: 81
      }
    ]
  },
  {
    id: 'sportybet-jackpot',
    name: 'SportyBet Jackpot',
    slug: 'sportybet-jackpot',
    gamesCount: 12,
    price: 340,
    entryFee: 'KES 50',
    estimatedPool: 'KES 5,000,000',
    nextGameStartTime: 'Starts Saturday: 14:00 EAT (Nairobi)',
    submissionsFill: '84%',
    premiumCount: '3,110+',
    fixtures: [
      {
        id: 401,
        fixtureNumber: 1,
        homeTeam: 'West Ham',
        awayTeam: 'Crystal Palace',
        prediction: 'Double Chance (X2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-20T14:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: 1,
        awayScore: 1,
        confidence: 78
      },
      {
        id: 402,
        fixtureNumber: 2,
        homeTeam: 'Wolves',
        awayTeam: 'Leeds',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-20T14:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: 1,
        awayScore: 1,
        confidence: 81
      },
      {
        id: 403,
        fixtureNumber: 3,
        homeTeam: 'Manchester United',
        awayTeam: 'Chelsea',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-20T16:30:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: 2,
        awayScore: 2,
        confidence: 83
      },
      {
        id: 404,
        fixtureNumber: 4,
        homeTeam: 'Alaves',
        awayTeam: 'Sevilla',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-20T14:15:00Z',
        leagueName: 'La Liga',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        homeScore: 1,
        awayScore: 1,
        confidence: 76
      },
      {
        id: 405,
        fixtureNumber: 5,
        homeTeam: 'Stade Brestois 29',
        awayTeam: 'Nice',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-20T15:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 4,
        awayScore: 4,
        confidence: 74
      },
      {
        id: 406,
        fixtureNumber: 6,
        homeTeam: 'Valencia',
        awayTeam: 'Athletic Club',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-20T16:30:00Z',
        leagueName: 'La Liga',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        homeScore: 2,
        awayScore: 2,
        confidence: 79
      },
      {
        id: 407,
        fixtureNumber: 7,
        homeTeam: 'Lens',
        awayTeam: 'Lille',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-20T19:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 3,
        awayScore: 3,
        confidence: 82
      },
      {
        id: 408,
        fixtureNumber: 8,
        homeTeam: 'Lazio',
        awayTeam: 'AS Roma',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-21T16:00:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: 0,
        awayScore: 0,
        confidence: 80
      },
      {
        id: 409,
        fixtureNumber: 9,
        homeTeam: 'Rayo Vallecano',
        awayTeam: 'Celta Vigo',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-21T14:15:00Z',
        leagueName: 'La Liga',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        homeScore: 1,
        awayScore: 1,
        confidence: 71
      },
      {
        id: 410,
        fixtureNumber: 10,
        homeTeam: 'Bournemouth',
        awayTeam: 'Newcastle',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-21T14:30:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: 0,
        awayScore: 0,
        confidence: 73
      },
      {
        id: 411,
        fixtureNumber: 11,
        homeTeam: 'Auxerre',
        awayTeam: 'Toulouse',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-21T15:00:00Z',
        leagueName: 'Ligue 1',
        leagueFlag: '🇫🇷',
        countryName: 'France',
        homeScore: 1,
        awayScore: 1,
        confidence: 70
      },
      {
        id: 412,
        fixtureNumber: 12,
        homeTeam: 'Fiorentina',
        awayTeam: 'Como',
        prediction: 'Home Win (1)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-21T11:30:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        homeScore: 1,
        awayScore: 1,
        confidence: 85
      }
    ]
  },
  {
    id: 'betpawa-pick-jackpot',
    name: 'BetPawa Pick 13 Jackpot',
    slug: 'betpawa-pick-jackpot',
    gamesCount: 13,
    price: 400,
    entryFee: 'KES 10',
    estimatedPool: 'KES 10,000,000',
    nextGameStartTime: 'Starts Tuesday: 19:00 EAT (Nairobi)',
    submissionsFill: '88%',
    premiumCount: '5,420+',
    fixtures: [
      {
        id: 501,
        fixtureNumber: 1,
        homeTeam: 'Brentford',
        awayTeam: 'Aston Villa',
        prediction: 'Double Chance (12)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-23T19:00:00Z',
        leagueName: 'League Cup',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        homeScore: 1,
        awayScore: 1,
        confidence: 84
      },
      {
        id: 502,
        fixtureNumber: 2,
        homeTeam: 'Juventus',
        awayTeam: 'Borussia Dortmund',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-23T19:45:00Z',
        leagueName: 'UEFA Champions League',
        leagueFlag: '🇪🇺',
        countryName: 'Europe',
        homeScore: 4,
        awayScore: 4,
        confidence: 79
      },
      {
        id: 503,
        fixtureNumber: 3,
        homeTeam: 'Tottenham',
        awayTeam: 'Villarreal',
        prediction: 'Double Chance (X1)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-23T19:45:00Z',
        leagueName: 'UEFA Champions League',
        leagueFlag: '🇪🇺',
        countryName: 'Europe',
        homeScore: 1,
        awayScore: 1,
        confidence: 81
      },
      {
        id: 504,
        fixtureNumber: 4,
        homeTeam: 'Velez Sarsfield',
        awayTeam: 'Racing Club',
        prediction: 'Double Chance (X2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-23T21:00:00Z',
        leagueName: 'CONMEBOL Libertadores',
        leagueFlag: '🌎',
        countryName: 'South America',
        homeScore: 0,
        awayScore: 0,
        confidence: 76
      },
      {
        id: 505,
        fixtureNumber: 5,
        homeTeam: 'Lanus',
        awayTeam: 'Fluminense',
        prediction: 'Double Chance (1X)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-23T21:00:00Z',
        leagueName: 'CONMEBOL Sudamericana',
        leagueFlag: '🌎',
        countryName: 'South America',
        homeScore: 1,
        awayScore: 1,
        confidence: 72
      },
      {
        id: 506,
        fixtureNumber: 6,
        homeTeam: 'Slavia Praha',
        awayTeam: 'BodoGlimt',
        prediction: 'Home Win (1)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-24T19:00:00Z',
        leagueName: 'UEFA Champions League',
        leagueFlag: '🇪🇺',
        countryName: 'Europe',
        homeScore: 2,
        awayScore: 2,
        confidence: 75
      },
      {
        id: 507,
        fixtureNumber: 7,
        homeTeam: 'Ajax',
        awayTeam: 'Inter',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-24T19:00:00Z',
        leagueName: 'UEFA Champions League',
        leagueFlag: '🇪🇺',
        countryName: 'Europe',
        homeScore: 0,
        awayScore: 0,
        confidence: 82
      },
      {
        id: 508,
        fixtureNumber: 8,
        homeTeam: 'New York City FC',
        awayTeam: 'Columbus Crew',
        prediction: 'Double Chance (X2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-24T19:30:00Z',
        leagueName: 'Major League Soccer',
        leagueFlag: '🇺🇸',
        countryName: 'USA',
        homeScore: 3,
        awayScore: 3,
        confidence: 80
      },
      {
        id: 509,
        fixtureNumber: 9,
        homeTeam: 'Racing Club',
        awayTeam: 'River Plate',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-24T21:00:00Z',
        leagueName: 'Copa Argentina',
        leagueFlag: '🇦🇷',
        countryName: 'Argentina',
        confidence: 71
      },
      {
        id: 510,
        fixtureNumber: 10,
        homeTeam: 'Club Brugge KV',
        awayTeam: 'Monaco',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-24T19:00:00Z',
        leagueName: 'UEFA Champions League',
        leagueFlag: '🇪🇺',
        countryName: 'Europe',
        homeScore: 4,
        awayScore: 4,
        confidence: 74
      },
      {
        id: 511,
        fixtureNumber: 11,
        homeTeam: 'FC Copenhagen',
        awayTeam: 'Bayer Leverkusen',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-24T19:00:00Z',
        leagueName: 'UEFA Champions League',
        leagueFlag: '🇪🇺',
        countryName: 'Europe',
        homeScore: 2,
        awayScore: 2,
        confidence: 83
      },
      {
        id: 512,
        fixtureNumber: 12,
        homeTeam: 'Eintracht Frankfurt',
        awayTeam: 'Galatasaray',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-24T19:00:00Z',
        leagueName: 'UEFA Champions League',
        leagueFlag: '🇪🇺',
        countryName: 'Europe',
        homeScore: 5,
        awayScore: 5,
        confidence: 79
      },
      {
        id: 513,
        fixtureNumber: 13,
        homeTeam: 'Newcastle',
        awayTeam: 'Barcelona',
        prediction: 'Away Win (2)',
        result: 'won',
        status: 'FT',
        kickoffTime: '2025-09-24T19:00:00Z',
        leagueName: 'UEFA Champions League',
        leagueFlag: '🇪🇺',
        countryName: 'Europe',
        homeScore: 1,
        awayScore: 1,
        confidence: 81
      }
    ]
  },
  {
    id: 'odibet-laki-tatu',
    name: 'OdiBets Laki Tatu Jackpot',
    slug: 'odibet-laki-tatu',
    gamesCount: 10,
    price: 300,
    entryFee: 'KES 15',
    estimatedPool: 'KES 300,000',
    nextGameStartTime: 'Starts Saturday: 16:00 EAT (Nairobi)',
    submissionsFill: '82%',
    premiumCount: '4,120+',
    fixtures: [
      {
        id: 601,
        fixtureNumber: 1,
        homeTeam: 'Juventus',
        awayTeam: 'Atalanta',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T16:00:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        confidence: 80
      },
      {
        id: 602,
        fixtureNumber: 2,
        homeTeam: 'Borussia Mönchengladbach',
        awayTeam: 'Eintracht Frankfurt',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T16:00:00Z',
        leagueName: 'Bundesliga',
        leagueFlag: '🇩🇪',
        countryName: 'Germany',
        confidence: 74
      },
      {
        id: 603,
        fixtureNumber: 3,
        homeTeam: 'Nottingham Forest',
        awayTeam: 'Sunderland',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T16:00:00Z',
        leagueName: 'Premier League',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 71
      },
      {
        id: 604,
        fixtureNumber: 4,
        homeTeam: 'Fatih Karagümrük',
        awayTeam: 'Trabzonspor',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T16:00:00Z',
        leagueName: 'Süper Lig',
        leagueFlag: '🇹🇷',
        countryName: 'Turkey',
        confidence: 78
      },
      {
        id: 605,
        fixtureNumber: 5,
        homeTeam: 'Aldosivi',
        awayTeam: 'Argentinos JRS',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T18:00:00Z',
        leagueName: 'Liga Profesional Argentina',
        leagueFlag: '🇦🇷',
        countryName: 'Argentina',
        confidence: 69
      },
      {
        id: 606,
        fixtureNumber: 6,
        homeTeam: 'Cagliari',
        awayTeam: 'Inter',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T18:45:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇮🇹',
        countryName: 'Italy',
        confidence: 85
      },
      {
        id: 607,
        fixtureNumber: 7,
        homeTeam: 'Sligo Rovers',
        awayTeam: 'St Patrick\'s Athl.',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T18:45:00Z',
        leagueName: 'Premier Division',
        leagueFlag: '🇮🇪',
        countryName: 'Ireland',
        confidence: 72
      },
      {
        id: 608,
        fixtureNumber: 8,
        homeTeam: 'Las Palmas',
        awayTeam: 'Almeria',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T12:00:00Z',
        leagueName: 'Segunda División',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        confidence: 77
      },
      {
        id: 609,
        fixtureNumber: 9,
        homeTeam: 'Toronto FC',
        awayTeam: 'Inter Miami',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-27T19:30:00Z',
        leagueName: 'Major League Soccer',
        leagueFlag: '🇺🇸',
        countryName: 'USA',
        confidence: 82
      },
      {
        id: 610,
        fixtureNumber: 10,
        homeTeam: 'Atletico-MG',
        awayTeam: 'Mirassol',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-28T19:00:00Z',
        leagueName: 'Serie A',
        leagueFlag: '🇧🇷',
        countryName: 'Brazil',
        confidence: 70
      }
    ]
  },
  {
    id: 'mozzart-super-daily',
    name: 'Mozzart Super Daily Jackpot',
    slug: 'mozzart-super-daily',
    gamesCount: 16,
    price: 350,
    entryFee: 'KES 50',
    estimatedPool: 'KES 20,000,000',
    nextGameStartTime: 'Starts Monday: 15:00 EAT (Nairobi)',
    submissionsFill: '90%',
    premiumCount: '6,180+',
    fixtures: [
      {
        id: 701,
        fixtureNumber: 1,
        homeTeam: 'Csikszereda',
        awayTeam: 'Metoglobus',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T15:00:00Z',
        leagueName: 'Liga I',
        leagueFlag: '🇷🇴',
        countryName: 'Romania',
        confidence: 78
      },
      {
        id: 702,
        fixtureNumber: 2,
        homeTeam: 'Arda Kardzhali',
        awayTeam: 'Cherno More Varna',
        prediction: 'Double Chance (X1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T15:00:00Z',
        leagueName: 'First League',
        leagueFlag: '🇧🇬',
        countryName: 'Bulgaria',
        confidence: 75
      },
      {
        id: 703,
        fixtureNumber: 3,
        homeTeam: 'AEK Larnaca',
        awayTeam: 'Aris',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T16:00:00Z',
        leagueName: '1. Division',
        leagueFlag: '🇨🇾',
        countryName: 'Cyprus',
        confidence: 71
      },
      {
        id: 704,
        fixtureNumber: 4,
        homeTeam: 'Randers FC',
        awayTeam: 'FC Nordsjaelland',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T17:00:00Z',
        leagueName: 'Superliga',
        leagueFlag: '🇩🇰',
        countryName: 'Denmark',
        confidence: 74
      },
      {
        id: 705,
        fixtureNumber: 5,
        homeTeam: 'IFK Varnamo',
        awayTeam: 'Halmstad',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T17:00:00Z',
        leagueName: 'Allsvenskan',
        leagueFlag: '🇸🇪',
        countryName: 'Sweden',
        confidence: 69
      },
      {
        id: 706,
        fixtureNumber: 6,
        homeTeam: 'IFK Norrkoping',
        awayTeam: 'AIK Stockholm',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T17:00:00Z',
        leagueName: 'Allsvenskan',
        leagueFlag: '🇸🇪',
        countryName: 'Sweden',
        confidence: 80
      },
      {
        id: 707,
        fixtureNumber: 7,
        homeTeam: 'Jong AZ',
        awayTeam: 'De Graafschap',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T18:00:00Z',
        leagueName: 'Eerste Divisie',
        leagueFlag: '🇳🇱',
        countryName: 'Netherlands',
        confidence: 76
      },
      {
        id: 708,
        fixtureNumber: 8,
        homeTeam: 'Jong PSV',
        awayTeam: 'Den Bosch',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T18:00:00Z',
        leagueName: 'Eerste Divisie',
        leagueFlag: '🇳🇱',
        countryName: 'Netherlands',
        confidence: 73
      },
      {
        id: 709,
        fixtureNumber: 9,
        homeTeam: 'Dinamo Bucuresti',
        awayTeam: 'Farul Constanta',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T18:30:00Z',
        leagueName: 'Liga I',
        leagueFlag: '🇷🇴',
        countryName: 'Romania',
        confidence: 82
      },
      {
        id: 710,
        fixtureNumber: 10,
        homeTeam: 'Burgos',
        awayTeam: 'Granada CF',
        prediction: 'Double Chance (X1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T18:30:00Z',
        leagueName: 'Segunda División',
        leagueFlag: '🇪🇸',
        countryName: 'Spain',
        confidence: 71
      },
      {
        id: 711,
        fixtureNumber: 11,
        homeTeam: 'Drogheda United',
        awayTeam: 'Shelbourne',
        prediction: 'Away Win (2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T18:45:00Z',
        leagueName: 'Premier Division',
        leagueFlag: '🇮🇪',
        countryName: 'Ireland',
        confidence: 79
      },
      {
        id: 712,
        fixtureNumber: 12,
        homeTeam: 'Finn Harps',
        awayTeam: 'Wexford',
        prediction: 'Double Chance (X2)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T18:45:00Z',
        leagueName: 'First Division',
        leagueFlag: '🇮🇪',
        countryName: 'Ireland',
        confidence: 70
      },
      {
        id: 713,
        fixtureNumber: 13,
        homeTeam: 'Millwall',
        awayTeam: 'Watford',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T19:00:00Z',
        leagueName: 'Championship',
        leagueFlag: '🇬🇧',
        countryName: 'England',
        confidence: 75
      },
      {
        id: 714,
        fixtureNumber: 14,
        homeTeam: 'Valur Reykjavik',
        awayTeam: 'Breidablik',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T19:15:00Z',
        leagueName: 'Úrvalsdeild',
        leagueFlag: '🇮🇸',
        countryName: 'Iceland',
        confidence: 72
      },
      {
        id: 715,
        fixtureNumber: 15,
        homeTeam: 'Estudiantes L.P.',
        awayTeam: 'Defensa Y Justicia',
        prediction: 'Home Win (1)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-22T21:00:00Z',
        leagueName: 'Liga Profesional Argentina',
        leagueFlag: '🇦🇷',
        countryName: 'Argentina',
        confidence: 81
      },
      {
        id: 716,
        fixtureNumber: 16,
        homeTeam: 'Belgrano Cordoba',
        awayTeam: 'Newells Old Boys',
        prediction: 'Double Chance (1X)',
        result: 'pending',
        status: 'NS',
        kickoffTime: '2025-09-23T00:00:00Z',
        leagueName: 'Liga Profesional Argentina',
        leagueFlag: '🇦🇷',
        countryName: 'Argentina',
        confidence: 74
      }
    ]
  }
];

export const jackpotsData: JackpotConfig[] = applyDynamicKenyanSchedule(rawJackpotsData);

